Add humanmade/coding-standards + Fix coding style errors
humanmade/psalm-plugin-wordpress pull request #41
Opened 2022-10-26 21:37 UTC by mcaskill

While testing this library and its open pull requests, I noticed that a `phpcs` binary was missing (for the Composer script `@cs-check`).

#### Added

* Dependency on [humanmade/coding-standards]
* [EditorConfig ruleset file](.editorconfig)
* [PHPCS ruleset file](phpcs.xml.dist)

#### Changed

* Fixed errors and warnings raised by PHPCS.
* Split classes into their own files:
  * `TestConfig` from `BaseTestCase`
  * `HookNodeVisitor` and `HookNotFound` from `Plugin`

[humanmade/coding-standards]: https://github.com/humanmade/coding-standards
[squizlabs/PHP_CodeSniffer]: https://github.com/squizlabs/PHP_CodeSniffer

2022-10-27 14:35 UTC, mcaskill commented
Ok. I can revert that change.

Its unfortunate about your private fork, I just finished work on a feature branch to support Psalm v5 that I was about to propose as a follow up to this pull request 😆

2022-10-27 16:58 UTC, mcaskill commented
I've pitched your idea to to Joe Hoyle and Human Made (by email) and Orklah (by Symfony's Slack).

2022-10-27 17:29 UTC, mcaskill commented
Reply from Orklah:

> I have no objection to adding this project to the Psalm namespace. I don't have all permissions on it myself but if Human Made and Joe Hoyle are up for it, I'll bring the discussion to Matt and Bruce, I'm sure it will be a formality. I'm not sure what that entails about packagist namespace though.
> However, having this under Psalm's namespace doesn't mean it will automatically get better support, at least from our end. As you probably already know, our time is quite limited and we can't offer a lot more than visibility on the official Psalm's namespace
> — From private conversation, symfony.com/slack

2022-10-28 00:13 UTC, ntwb requested changes
Just one trivial change please in the battle of tabs vs spaces ;)

2022-10-28 00:15 UTC, ntwb commented
Hey,

Unsure hat HMs stance on maintaining this projectin the future, but I'm happy to help land a few of these PRs so a new release tagged and pushed out

2022-10-28 00:25 UTC, mcaskill commented on .editorconfig
> +indent_size = 2
I'll merge this one in. I was using this ruleset since it aligned with the current mix of tab and space indentation.

2022-10-28 00:27 UTC, ntwb commented on .editorconfig
> +indent_size = 2
I did check `https://github.com/humanmade/psalm-plugin-wordpress/blob/master/Plugin.php`

Indentation is currently tabs and looks correct, spaces are used in comments and code for alignment though

2022-10-28 00:36 UTC, mcaskill commented
> Unsure hat HMs stance on maintaining this project in the future, but I'm happy to help land a few of these PRs so a new release tagged and pushed out

Hi @ntwb, thanks for your help.

2022-10-28 00:42 UTC, ntwb approved these changes
Looks good, thanks @mcaskill

2022-10-28 00:42 UTC, merged

2022-10-28 07:12 UTC, joehoyle commented
@mcaskill @kkmuffme thanks for reaching out! First off, thanks for all the contributions! This project is not exactly "abandoned", but like "on the sidelines", as it's more of a _my_ project rather than Human Made, company wide. As such, I only get intermittent chances to review and merge things, or improve things. 

This plugin is still pretty Alpha stages, so we are not using it in "production" by any means. I'd be happy to add you as GitHub committers if that would help too.

I'll also raise the discussion of transferring to Psalm's org, if that's the preferred approach.

Also thank you @ntwb for helping out! Are you using this at all?

2022-10-28 07:32 UTC, ntwb commented
> Also thank you @ntwb for helping out! Are you using this at all?

Only using on side projects here, it's crazy if I run it on the the project I'm working on at HM, but maybe one day I can formally add it to the project 🤞🏼

2022-11-01 07:58 UTC, joehoyle commented
@kkmuffme ok sounds good!