V5 compatibility and features
humanmade/psalm-plugin-wordpress pull request #49
Opened 2023-11-29 14:44 UTC by kkmuffme

@mcaskill finally I had some time to PR it; my fork was quite different already and I had to remove a couple things that are internal, so it took a bit more time.

It's been almost 2 years since I wrote some of the code, and I'm much more familiar with psalm's code base now than I was then, so I already see a variety of things that can be improved upon eventually.

If you could take a quick look and run this branch for a few days in your codebase, to identify any issues/points you want to change upon, that would be great.

Otherwise, I'd say we merge this, and then add/merge the few changes of https://github.com/psalm/psalm-plugin-wordpress/pull/42/files, which aren't part of this PR already, to it (if you don't want to do that, I'm fine to do that chore)

--

This PR adds compatibility with psalm v5, new phpparser version (afair 4.16 or something), support for dynamic hook names, some support for cron hooks, errors for deprecated hooks, handling for hooks without docs, and tons of other stuff.

Fix https://github.com/psalm/psalm-plugin-wordpress/issues/18

2023-11-29 15:43 UTC, mcaskill requested changes
I've performed a cursory review of the changes. Looks good. A lot to absorb. I've perform a deeper dive as soon as I can.

2023-11-29 15:43 UTC, mcaskill commented on composer.json
[psalm/plugin-phpunit](https://github.com/psalm/psalm-plugin-phpunit) should require [`^0.18.4`](https://github.com/psalm/psalm-plugin-phpunit/releases/tag/0.18.4) which allows Psalm 5.

2023-11-29 15:43 UTC, mcaskill commented on Plugin.php
There's a handful of occurrences of inconsistent coding style.

```diff
- });
+ } );
```

2023-11-29 15:43 UTC, mcaskill commented on Plugin.php
> +		}
For consistency, there should be a comment for `requireAllParams`, similar to the ones for the other options.
Furthermore, the `requireAllParams` option should be documented in the `README.md`.

2023-11-29 15:43 UTC, mcaskill commented on Plugin.php
There's a few changes on the `master` branch that you are going to need to rebase/include:

* c4dcb85 — Add `hooks.json` file as candidate for custom hooks.
* bd97269 — Add `stubs/globals.php` to stub files (#44)

2023-11-30 05:42 UTC, kkmuffme commented on Plugin.php
Master branch is broken compeltely tbh - https://github.com/psalm/psalm-plugin-wordpress/commit/b6ceeefce947c0d60170aa7f2496334fbc6761b0 the @var you added was wrong and it's not loading the hooks at all, bc this is a SimpleXMLElement, not a string.

If ixed this in this branch now too.

Will rebase it anyway though

2023-11-30 05:46 UTC, kkmuffme commented on Plugin.php
Unable to find where this is

2023-11-30 05:58 UTC, kkmuffme commented on Plugin.php
> +		}
Thanks, done!

2023-11-30 16:05 UTC, mcaskill commented on Plugin.php
Let's leave this thread open. I'll do a pass of edits for coding style.

2023-12-01 19:20 UTC, paulshryock commented on Plugin.php
Is this not something that `composer cs-fix` would fix?

2023-12-01 19:22 UTC, mcaskill commented on Plugin.php
Most likely

2023-12-02 09:30 UTC, kkmuffme commented on Plugin.php
I think we should add a pipeline for these cs fixes for github later, just like psalm has.
And maybe also change the cs ruleset to psalm's as that would make more sense, bc now it's some weird in between of WP and psalm.

At a later point in master branch though, not part of this PR.

2023-12-15 00:21 UTC, kkmuffme commented on Plugin.php
@mcaskill @paulshryock any further questions, otherwise I think we can merge this and release a new version

For the CI stuff I created an issue https://github.com/psalm/psalm-plugin-wordpress/issues/50 so this can be tackled after the merge
I guess it's straightforward and shouldn't take long, so we can add that and finally create a release in the next 2 weeks before the end of the year.

2023-12-15 15:19 UTC, mcaskill commented on Plugin.php
Good idea with the separate issue.

Unfortunately, after all, I won't be able to test this PR until maybe January.
You have my approval to merge this PR. Should be good.

2023-12-15 15:20 UTC, mcaskill approved these changes

2023-12-17 11:14 UTC, merged

2025-09-03 21:14 UTC, joehoyle commented on Plugin.php
> +								'Hook "' . $hook_name . '" does not accept any args, but the default number of args of add_action is 1. Please pass 0 as 4th argument',
This seems like a very bizarre error to me. Is the expectation that every have to do `add_action( 'init', 'my_plugin_init', 10, 0 )`?

2025-09-04 07:57 UTC, kkmuffme commented on Plugin.php
> +								'Hook "' . $hook_name . '" does not accept any args, but the default number of args of add_action is 1. Please pass 0 as 4th argument',
Yes. This isn't a 100% necessity, but so are most issues on psalm level 0/Mixed issues, I guess this could be made to only report on the strictest level

2025-09-07 09:38 UTC, kkmuffme commented on Plugin.php
> +								'Hook "' . $hook_name . '" does not accept any args, but the default number of args of add_action is 1. Please pass 0 as 4th argument',
I remembered why: depending on the callback used, this could result in a fatal error:
ArgumentCountError: ... expects at most 0 arguments, 1 given

and this error is something that is otherwise reported by psalm too (TooManyArguments or something)

2025-09-07 13:17 UTC, joehoyle commented on Plugin.php
> +								'Hook "' . $hook_name . '" does not accept any args, but the default number of args of add_action is 1. Please pass 0 as 4th argument',
Ah I see-- do we inspect the hook though to see if it _will_ actually pass an arg, rather than just relying on the default? E.g. I think "init" doesn't pass any args

2025-09-08 05:51 UTC, kkmuffme commented on Plugin.php
> +								'Hook "' . $hook_name . '" does not accept any args, but the default number of args of add_action is 1. Please pass 0 as 4th argument',
>do we inspect the hook though to see if it will actually pass an arg, rather than just relying on the default?

Afair no, and the reason for that was that I got burnt with that before: various plugins (including WooCommerce at times) sometimes call hooks with a different number of args, which again resulted in a (rare) fatal error.
Besides that, it's risky with dynamic hook names to get a false negative.
Basically, setting the 0 parameter is just ensuring you won't randomly get a fatal